fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    influxdb: "https://github.com/n1tr0g/golja-influxdb.git"

  symlinks:
    profile_influxdb: "#{source_dir}"
